# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18cffa5ace6b2ad71ef282eedbc12240ae72cd5afb915f54ef73de729be350a81849c02d0eb82fd8aca125d3873a511ad4f722a438fb07b215ac9569b83bd885

test:
  secret_key_base: 40d38098e1e53dad4e285ed2edca523bc5c31fdc4cb6e7ff8b3913e50e55ff956e16bbb62b30e89da8e72c4764ec91065bbb89d711ceaf3e6b06d3799c1b7f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
